In [1]:
import pandas as pd

In [2]:
from sklearn import preprocessing

scaler = preprocessing.MinMaxScaler()

In [3]:
account_list = pd.read_csv('./1Kvertices-100Kedges/accounts.csv')

In [4]:
account_list

,ACCOUNT_ID,CUSTOMER_ID,INIT_BALANCE,COUNTRY,ACCOUNT_TYPE,IS_FRAUD,TX_BEHAVIOR_ID
0,0,C_0,184.44,US,I,False,1
1,1,C_1,175.80,US,I,False,1
2,2,C_2,142.06,US,I,False,1
3,3,C_3,125.89,US,I,False,1
4,4,C_4,151.13,US,I,False,1
...,...,...,...,...,...,...,...
995,995,C_995,208.72,US,I,True,5
996,996,C_996,225.17,US,I,True,5
997,997,C_997,385.88,US,I,True,5
998,998,C_998,389.72,US,I,True,5
999,999,C_999,296.08,US,I,True,5

In [5]:
(account_list.CUSTOMER_ID == 'C_' + account_list.ACCOUNT_ID.astype(str)).all()

True

__Estrutura do `accounts.csv`__

- __ACCOUNT_ID__: identificador único.
- __CUSTOMER_ID__: outro identificador único
- __INIT_BALANCE__: saldo inicial da conta
- __COUNTRY__: país da conta
- __ACCOUNT_TYPE__: tipo de conta
- __IS_FRAUD__: Se é uma conta fraudulenta ou não
- __TX_BEHAVIOUR_ID__: ??

In [6]:
transactions = pd.read_csv('./1Kvertices-100Kedges/transactions.csv')

In [7]:
transactions

,TX_ID,SENDER_ACCOUNT_ID,RECEIVER_ACCOUNT_ID,TX_TYPE,TX_AMOUNT,TIMESTAMP,IS_FRAUD,ALERT_ID
0,1,959,450,TRANSFER,406.85,0,False,-1
1,2,245,324,TRANSFER,469.41,0,False,-1
2,3,507,980,TRANSFER,17.25,0,False,-1
3,4,507,919,TRANSFER,17.25,0,False,-1
4,5,507,962,TRANSFER,17.25,0,False,-1
...,...,...,...,...,...,...,...,...
117528,117529,627,555,TRANSFER,1693722.87,199,False,-1
117529,117530,386,770,TRANSFER,361.01,199,False,-1
117530,117531,649,165,TRANSFER,460.04,199,False,-1
117531,117532,151,179,TRANSFER,593.30,199,False,-1
117532,117533,650,871,TRANSFER,549.03,199,False,-1

In [8]:
transactions[transactions.TIMESTAMP == 1]

,TX_ID,SENDER_ACCOUNT_ID,RECEIVER_ACCOUNT_ID,TX_TYPE,TX_AMOUNT,TIMESTAMP,IS_FRAUD,ALERT_ID
306,307,342,980,TRANSFER,596.59,1,False,-1
307,308,606,498,TRANSFER,17.45,1,False,-1
308,309,606,841,TRANSFER,17.45,1,False,-1
309,310,606,996,TRANSFER,17.45,1,False,-1
310,311,606,216,TRANSFER,17.45,1,False,-1
...,...,...,...,...,...,...,...,...
752,753,554,176,TRANSFER,488.95,1,False,-1
753,754,334,991,TRANSFER,17.65,1,False,-1
754,755,544,132,TRANSFER,404.10,1,False,-1
755,756,728,583,TRANSFER,165.03,1,False,-1
756,757,443,242,TRANSFER,493.44,1,False,-1

In [9]:
def scaleColumns(df, cols_to_scale):
    for col in cols_to_scale:
        df[col] = pd.DataFrame(scaler.fit_transform(pd.DataFrame(df[col])),columns=[col])
    return df

In [10]:
transactions[transactions.IS_FRAUD == True]

,TX_ID,SENDER_ACCOUNT_ID,RECEIVER_ACCOUNT_ID,TX_TYPE,TX_AMOUNT,TIMESTAMP,IS_FRAUD,ALERT_ID
1863,1864,732,608,TRANSFER,2.88,4,True,14
3520,3521,813,608,TRANSFER,3.72,6,True,14
4332,4333,814,608,TRANSFER,3.66,8,True,14
7875,7876,488,889,TRANSFER,4.48,14,True,11
9574,9575,811,889,TRANSFER,3.95,16,True,11
...,...,...,...,...,...,...,...,...
112735,112736,956,749,TRANSFER,18.96,191,True,31
113541,113542,749,991,TRANSFER,18.96,193,True,31
115049,115050,985,996,TRANSFER,18.96,195,True,31
115785,115786,991,985,TRANSFER,18.96,196,True,31
116271,116272,351,368,TRANSFER,12.52,197,True,26

In [11]:
transactions['SENDER_X'] = str(account_list[account_list.ACCOUNT_ID == 732].values[0])

In [12]:
transactions

,TX_ID,SENDER_ACCOUNT_ID,RECEIVER_ACCOUNT_ID,TX_TYPE,TX_AMOUNT,TIMESTAMP,IS_FRAUD,ALERT_ID,SENDER_X
0,1,959,450,TRANSFER,406.85,0,False,-1,[732 'C_732' 267.9 'US' 'I' True 2]
1,2,245,324,TRANSFER,469.41,0,False,-1,[732 'C_732' 267.9 'US' 'I' True 2]
2,3,507,980,TRANSFER,17.25,0,False,-1,[732 'C_732' 267.9 'US' 'I' True 2]
3,4,507,919,TRANSFER,17.25,0,False,-1,[732 'C_732' 267.9 'US' 'I' True 2]
4,5,507,962,TRANSFER,17.25,0,False,-1,[732 'C_732' 267.9 'US' 'I' True 2]
...,...,...,...,...,...,...,...,...,...
117528,117529,627,555,TRANSFER,1693722.87,199,False,-1,[732 'C_732' 267.9 'US' 'I' True 2]
117529,117530,386,770,TRANSFER,361.01,199,False,-1,[732 'C_732' 267.9 'US' 'I' True 2]
117530,117531,649,165,TRANSFER,460.04,199,False,-1,[732 'C_732' 267.9 'US' 'I' True 2]
117531,117532,151,179,TRANSFER,593.30,199,False,-1,[732 'C_732' 267.9 'US' 'I' True 2]
117532,117533,650,871,TRANSFER,549.03,199,False,-1,[732 'C_732' 267.9 'US' 'I' True 2]

In [13]:
transactions[['TX_AMOUNT', 'TIMESTAMP', 'ALERT_ID']] = scaler.fit_transform(transactions[['TX_AMOUNT', 'TIMESTAMP', 'ALERT_ID']])
account_list[['INIT_BALANCE', 'TX_BEHAVIOR_ID']] = scaler.fit_transform(account_list[['INIT_BALANCE', 'TX_BEHAVIOR_ID']])

In [14]:
sender_accs = transactions[transactions.TIMESTAMP == 0].SENDER_ACCOUNT_ID.values.tolist()

In [15]:
sender_accs = sender_accs + transactions[transactions.TIMESTAMP == 0].RECEIVER_ACCOUNT_ID.values.tolist()

In [16]:
accs = list(set(sender_accs))

In [17]:
accs.sort()

In [18]:
accs.index(accs[1])

1

In [19]:
accs

[3,
 7,
 12,
 15,
 25,
 26,
 29,
 33,
 38,
 41,
 42,
 45,
 46,
 47,
 49,
 50,
 51,
 53,
 55,
 56,
 58,
 59,
 62,
 68,
 69,
 70,
 77,
 78,
 79,
 86,
 104,
 122,
 125,
 132,
 135,
 140,
 141,
 142,
 143,
 144,
 147,
 148,
 149,
 151,
 153,
 156,
 159,
 160,
 164,
 165,
 166,
 168,
 180,
 189,
 190,
 192,
 196,
 197,
 198,
 207,
 211,
 220,
 225,
 230,
 237,
 245,
 247,
 252,
 253,
 255,
 256,
 257,
 258,
 259,
 265,
 266,
 271,
 273,
 275,
 286,
 287,
 295,
 298,
 304,
 313,
 320,
 324,
 330,
 339,
 340,
 342,
 343,
 347,
 352,
 354,
 357,
 359,
 361,
 367,
 377,
 383,
 386,
 398,
 404,
 409,
 411,
 425,
 427,
 431,
 435,
 436,
 440,
 441,
 442,
 444,
 445,
 446,
 447,
 448,
 450,
 452,
 454,
 455,
 456,
 457,
 458,
 459,
 461,
 480,
 486,
 491,
 495,
 496,
 501,
 503,
 507,
 520,
 532,
 540,
 543,
 544,
 545,
 546,
 549,
 550,
 551,
 552,
 553,
 557,
 558,
 561,
 563,
 564,
 571,
 572,
 580,
 583,
 590,
 592,
 594,
 606,
 611,
 612,
 615,
 621,
 628,
 632,
 634,
 640,
 641,
 646,
 650,
 654,
 655,
 657,
 658,
 659,
 660,
 662,
 665,
 669,
 674,
 675,
 676,
 678,
 681,
 684,
 685,
 688,
 692,
 693,
 698,
 704,
 708,
 709,
 719,
 720,
 725,
 727,
 729,
 730,
 732,
 734,
 735,
 738,
 739,
 740,
 741,
 742,
 744,
 746,
 749,
 750,
 751,
 752,
 754,
 756,
 759,
 761,
 764,
 765,
 773,
 776,
 780,
 783,
 793,
 795,
 799,
 801,
 803,
 808,
 809,
 810,
 813,
 817,
 819,
 821,
 822,
 823,
 829,
 836,
 839,
 840,
 841,
 843,
 846,
 847,
 848,
 849,
 851,
 852,
 854,
 855,
 856,
 858,
 859,
 861,
 862,
 863,
 864,
 865,
 866,
 869,
 872,
 873,
 879,
 883,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 899,
 900,
 901,
 904,
 905,
 907,
 908,
 912,
 913,
 918,
 919,
 921,
 924,
 929,
 932,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 944,
 945,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 957,
 959,
 960,
 961,
 962,
 963,
 965,
 966,
 967,
 969,
 972,
 974,
 975,
 976,
 978,
 980,
 981,
 983,
 984,
 985,
 988,
 989,
 990,
 991,
 992,
 993,
 995,
 996,
 997,
 998,
 999]

In [20]:
accs_t_0 = account_list.loc[accs].reset_index().reset_index()[['level_0', 'index' ,'INIT_BALANCE', 'TX_BEHAVIOR_ID']]

In [21]:
accs_t_0

     level_0  index  INIT_BALANCE  TX_BEHAVIOR_ID
0          0      3      0.051977            0.00
1          1      7      0.060898            0.00
2          2     12      0.056578            0.00
3          3     15      0.050289            0.00
4          4     25      0.241341            0.25
..       ...    ...           ...             ...
333      333    995      0.218396            1.00
334      334    996      0.251447            1.00
335      335    997      0.574339            1.00
336      336    998      0.582054            1.00
337      337    999      0.393916            1.00

[338 rows x 4 columns]

In [22]:
def get_converted_index(old):
    return accs.index(old)

In [23]:
transactions_t0 = transactions[transactions.TIMESTAMP == 0]

In [24]:
transactions_t0.SENDER_ACCOUNT_ID = transactions_t0.SENDER_ACCOUNT_ID.apply(get_converted_index)

/tmp/ipykernel_2286/3744690933.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transactions_t0.SENDER_ACCOUNT_ID = transactions_t0.SENDER_ACCOUNT_ID.apply(get_converted_index)

In [25]:
transactions_t0

,TX_ID,SENDER_ACCOUNT_ID,RECEIVER_ACCOUNT_ID,TX_TYPE,TX_AMOUNT,TIMESTAMP,IS_FRAUD,ALERT_ID,SENDER_X
0,1,308,450,TRANSFER,0.000035,0.0,False,0.0,[732 'C_732' 267.9 'US' 'I' True 2]
1,2,65,324,TRANSFER,0.000041,0.0,False,0.0,[732 'C_732' 267.9 'US' 'I' True 2]
2,3,135,980,TRANSFER,0.000002,0.0,False,0.0,[732 'C_732' 267.9 'US' 'I' True 2]
3,4,135,919,TRANSFER,0.000002,0.0,False,0.0,[732 'C_732' 267.9 'US' 'I' True 2]
4,5,135,962,TRANSFER,0.000002,0.0,False,0.0,[732 'C_732' 267.9 'US' 'I' True 2]
...,...,...,...,...,...,...,...,...,...
301,302,182,735,TRANSFER,0.000012,0.0,False,0.0,[732 'C_732' 267.9 'US' 'I' True 2]
302,303,182,738,TRANSFER,0.000012,0.0,False,0.0,[732 'C_732' 267.9 'US' 'I' True 2]
303,304,120,411,TRANSFER,0.000049,0.0,False,0.0,[732 'C_732' 267.9 'US' 'I' True 2]
304,305,299,809,TRANSFER,0.000052,0.0,False,0.0,[732 'C_732' 267.9 'US' 'I' True 2]
305,306,306,773,TRANSFER,0.000042,0.0,False,0.0,[732 'C_732' 267.9 'US' 'I' True 2]

In [26]:
transactions_t0.RECEIVER_ACCOUNT_ID = transactions_t0.RECEIVER_ACCOUNT_ID.apply(get_converted_index)

/tmp/ipykernel_2286/3859453927.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  transactions_t0.RECEIVER_ACCOUNT_ID = transactions_t0.RECEIVER_ACCOUNT_ID.apply(get_converted_index)

In [27]:
transactions_t0

,TX_ID,SENDER_ACCOUNT_ID,RECEIVER_ACCOUNT_ID,TX_TYPE,TX_AMOUNT,TIMESTAMP,IS_FRAUD,ALERT_ID,SENDER_X
0,1,308,119,TRANSFER,0.000035,0.0,False,0.0,[732 'C_732' 267.9 'US' 'I' True 2]
1,2,65,86,TRANSFER,0.000041,0.0,False,0.0,[732 'C_732' 267.9 'US' 'I' True 2]
2,3,135,322,TRANSFER,0.000002,0.0,False,0.0,[732 'C_732' 267.9 'US' 'I' True 2]
3,4,135,285,TRANSFER,0.000002,0.0,False,0.0,[732 'C_732' 267.9 'US' 'I' True 2]
4,5,135,311,TRANSFER,0.000002,0.0,False,0.0,[732 'C_732' 267.9 'US' 'I' True 2]
...,...,...,...,...,...,...,...,...,...
301,302,182,203,TRANSFER,0.000012,0.0,False,0.0,[732 'C_732' 267.9 'US' 'I' True 2]
302,303,182,204,TRANSFER,0.000012,0.0,False,0.0,[732 'C_732' 267.9 'US' 'I' True 2]
303,304,120,105,TRANSFER,0.000049,0.0,False,0.0,[732 'C_732' 267.9 'US' 'I' True 2]
304,305,299,231,TRANSFER,0.000052,0.0,False,0.0,[732 'C_732' 267.9 'US' 'I' True 2]
305,306,306,221,TRANSFER,0.000042,0.0,False,0.0,[732 'C_732' 267.9 'US' 'I' True 2]

In [28]:
edge_index = transactions_t0[['SENDER_ACCOUNT_ID', 'RECEIVER_ACCOUNT_ID']]

In [29]:
edge_index.values['INIT_BALANCE', 'TX_BEHAVIOR_ID']

array([[308, 119],
       [ 65,  86],
       [135, 322],
       [135, 285],
       [135, 311],
       [135, 294],
       [135, 220],
       [135, 337],
       [135, 297],
       [ 91, 179],
       [251,  20],
       [279, 281],
       [279, 128],
       [279,  43],
       [279,  97],
       [279,  67],
       [279, 223],
       [279, 208],
       [279, 302],
       [279, 196],
       [279, 334],
       [279, 133],
       [279, 244],
       [279, 336],
       [279,  88],
       [279, 238],
       [279, 282],
       [279, 262],
       [279, 307],
       [279, 239],
       [ 46,  38],
       [117, 280],
       [ 73, 196],
       [ 66, 330],
       [ 72,  32],
       [ 52,  66],
       [169,  60],
       [ 42, 331],
       [ 71,  85],
       [273,  11],
       [157,  61],
       [ 15, 281],
       [142, 167],
       [ 14, 330],
       [174,  50],
       [211,  39],
       [202, 194],
       [206, 131],
       [148, 152],
       [ 78,   3],
       [ 78, 109],
       [ 78,  92],
       [ 78,  54],
       [ 78, 287],
       [ 78, 299],
       [  5, 163],
       [136, 331],
       [246, 280],
       [227, 235],
       [281, 130],
       [281, 127],
       [281,  37],
       [281, 225],
       [281, 272],
       [281,  40],
       [281, 264],
       [281, 274],
       [281, 333],
       [281, 312],
       [281, 318],
       [281, 106],
       [281, 289],
       [281, 277],
       [281,  15],
       [281, 198],
       [281, 291],
       [281,  29],
       [ 30, 191],
       [ 30, 335],
       [ 30, 160],
       [ 30, 127],
       [301,  24],
       [129, 329],
       [255,  79],
       [270,   2],
       [250, 285],
       [ 50, 288],
       [ 50,  62],
       [ 50, 174],
       [ 50, 336],
       [ 50, 180],
       [ 47, 332],
       [ 47,  92],
       [ 47, 236],
       [ 47, 197],
       [ 47, 293],
       [121, 331],
       [ 94, 324],
       [ 83, 330],
       [ 83, 147],
       [ 83, 141],
       [ 83, 110],
       [ 83, 216],
       [ 83, 253],
       [116,  80],
       [295,  56],
       [300,  26],
       [ 41, 256],
       [ 13, 275],
       [ 10, 260],
       [215, 271],
       [162, 132],
       [162, 136],
       [162,  98],
       [162,  83],
       [162, 335],
       [162, 268],
       [162, 307],
       [162,  76],
       [212,  80],
       [183, 330],
       [183, 331],
       [183, 178],
       [183, 266],
       [183, 164],
       [183, 227],
       [183, 234],
       [183, 193],
       [113, 186],
       [ 12, 312],
       [314,  54],
       [314,  55],
       [314,  63],
       [314,  93],
       [314, 332],
       [314, 137],
       [314, 214],
       [314, 123],
       [314, 333],
       [314, 149],
       [314, 305],
       [314, 320],
       [314, 336],
       [314, 216],
       [314, 321],
       [314, 283],
       [314, 308],
       [314, 205],
       [314, 241],
       [314,  36],
       [314,  48],
       [314,  74],
       [314, 309],
       [314, 266],
       [314, 324],
       [314, 237],
       [314, 315],
       [314, 328],
       [314, 192],
       [ 68, 301],
       [124, 213],
       [269, 288],
       [ 75, 257],
       [ 75, 302],
       [ 75, 267],
       [ 75,  25],
       [ 75, 337],
       [ 75, 143],
       [112, 222],
       [242,  81],
       [226, 102],
       [ 44, 332],
       [268, 284],
       [248,  19],
       [175,  27],
       [305, 190],
       [125, 329],
       [243, 284],
       [ 89, 288],
       [ 99,  31],
       [ 99,  51],
       [ 99,  95],
       [ 99,  84],
       [ 99, 161],
       [ 99, 316],
       [165, 281],
       [217, 111],
       [173, 329],
       [134, 101],
       [134, 231],
       [134, 309],
       [134,   4],
       [134, 242],
       [134, 249],
       [134, 319],
       [ 90, 322],
       [ 96,  85],
       [ 18,  87],
       [ 23, 323],
       [ 23, 310],
       [ 23, 302],
       [ 23, 321],
       [ 20, 232],
       [210, 132],
       [ 35, 326],
       [147, 156],
       [296, 185],
       [303,  11],
       [247, 100],
       [ 45, 218],
       [172,  93],
       [146, 144],
       [170, 270],
       [  0, 176],
       [ 92,  78],
       [286, 153],
       [ 22, 329],
       [ 22, 276],
       [ 22, 158],
       [ 22, 292],
       [145, 330],
       [140,  33],
       [118,  69],
       [  9, 319],
       [ 57,   7],
       [265,   8],
       [265,   6],
       [265, 171],
       [265,  82],
       [265, 136],
       [265, 207],
       [265, 249],
       [265, 295],
       [265, 304],
       [265, 327],
       [265, 328],
       [265,   9],
       [265, 278],
       [265, 299],
       [298, 230],
       [ 17, 258],
       [114, 108],
       [187,  49],
       [219, 322],
       [219, 224],
       [219, 206],
       [219, 122],
       [219, 188],
       [219,   1],
       [219, 228],
       [219,  59],
       [219, 321],
       [219, 316],
       [219,  77],
       [168, 138],
       [209,  58],
       [ 19,  53],
       [245, 230],
       [252, 155],
       [ 21, 259],
       [126, 311],
       [184, 177],
       [184,  28],
       [184,  66],
       [184, 201],
       [184, 107],
       [184, 315],
       [184, 240],
       [184, 104],
       [184, 195],
       [ 16, 325],
       [ 70, 302],
       [207, 231],
       [103,  34],
       [103, 200],
       [103, 257],
       [103, 164],
       [103,  64],
       [103, 149],
       [103, 233],
       [103, 229],
       [181,  39],
       [181,  28],
       [181, 263],
       [181, 317],
       [181, 215],
       [181, 261],
       [181, 298],
       [181, 290],
       [181, 199],
       [ 39, 154],
       [139, 331],
       [254, 189],
       [115, 150],
       [182, 159],
       [182, 151],
       [182, 272],
       [182, 333],
       [182, 166],
       [182, 313],
       [182, 327],
       [182, 203],
       [182, 204],
       [120, 105],
       [299, 231],
       [306, 221]])

In [30]:
edge_attr = transactions_t0[['TX_AMOUNT', 'TIMESTAMP', 'ALERT_ID']]

In [31]:
edge_attr.values

array([[3.54530267e-05, 0.00000000e+00, 0.00000000e+00],
       [4.09045232e-05, 0.00000000e+00, 0.00000000e+00],
       [1.50316999e-06, 0.00000000e+00, 0.00000000e+00],
       [1.50316999e-06, 0.00000000e+00, 0.00000000e+00],
       [1.50316999e-06, 0.00000000e+00, 0.00000000e+00],
       [1.50316999e-06, 0.00000000e+00, 0.00000000e+00],
       [1.50316999e-06, 0.00000000e+00, 0.00000000e+00],
       [1.50316999e-06, 0.00000000e+00, 0.00000000e+00],
       [1.50316999e-06, 0.00000000e+00, 0.00000000e+00],
       [3.74415681e-05, 0.00000000e+00, 0.00000000e+00],
       [4.03276545e-05, 0.00000000e+00, 0.00000000e+00],
       [6.36995514e-07, 0.00000000e+00, 0.00000000e+00],
       [6.36995514e-07, 0.00000000e+00, 0.00000000e+00],
       [6.36995514e-07, 0.00000000e+00, 0.00000000e+00],
       [6.36995514e-07, 0.00000000e+00, 0.00000000e+00],
       [6.36995514e-07, 0.00000000e+00, 0.00000000e+00],
       [6.36995514e-07, 0.00000000e+00, 0.00000000e+00],
       [6.36995514e-07, 0.00000000e+00, 0.00000000e+00],
       [6.36995514e-07, 0.00000000e+00, 0.00000000e+00],
       [6.36995514e-07, 0.00000000e+00, 0.00000000e+00],
       [6.36995514e-07, 0.00000000e+00, 0.00000000e+00],
       [6.36995514e-07, 0.00000000e+00, 0.00000000e+00],
       [6.36995514e-07, 0.00000000e+00, 0.00000000e+00],
       [6.36995514e-07, 0.00000000e+00, 0.00000000e+00],
       [6.36995514e-07, 0.00000000e+00, 0.00000000e+00],
       [6.36995514e-07, 0.00000000e+00, 0.00000000e+00],
       [6.36995514e-07, 0.00000000e+00, 0.00000000e+00],
       [6.36995514e-07, 0.00000000e+00, 0.00000000e+00],
       [6.36995514e-07, 0.00000000e+00, 0.00000000e+00],
       [6.36995514e-07, 0.00000000e+00, 0.00000000e+00],
       [3.79016688e-05, 0.00000000e+00, 0.00000000e+00],
       [4.67516366e-05, 0.00000000e+00, 0.00000000e+00],
       [4.72701213e-05, 0.00000000e+00, 0.00000000e+00],
       [3.97072156e-05, 0.00000000e+00, 0.00000000e+00],
       [4.62775934e-05, 0.00000000e+00, 0.00000000e+00],
       [2.84730895e-05, 0.00000000e+00, 0.00000000e+00],
       [4.10256482e-05, 0.00000000e+00, 0.00000000e+00],
       [3.78084287e-05, 0.00000000e+00, 0.00000000e+00],
       [4.70784127e-05, 0.00000000e+00, 0.00000000e+00],
       [3.04511741e-05, 0.00000000e+00, 0.00000000e+00],
       [2.69298350e-05, 0.00000000e+00, 0.00000000e+00],
       [4.88543318e-05, 0.00000000e+00, 0.00000000e+00],
       [3.61318495e-05, 0.00000000e+00, 0.00000000e+00],
       [5.17186331e-05, 0.00000000e+00, 0.00000000e+00],
       [4.40372166e-05, 0.00000000e+00, 0.00000000e+00],
       [4.98442454e-05, 0.00000000e+00, 0.00000000e+00],
       [6.36124111e-08, 0.00000000e+00, 0.00000000e+00],
       [3.56281787e-05, 0.00000000e+00, 0.00000000e+00],
       [3.58643288e-05, 0.00000000e+00, 0.00000000e+00],
       [1.72703339e-05, 0.00000000e+00, 0.00000000e+00],
       [1.72703339e-05, 0.00000000e+00, 0.00000000e+00],
       [1.72703339e-05, 0.00000000e+00, 0.00000000e+00],
       [1.72703339e-05, 0.00000000e+00, 0.00000000e+00],
       [1.72703339e-05, 0.00000000e+00, 0.00000000e+00],
       [1.72703339e-05, 0.00000000e+00, 0.00000000e+00],
       [2.11750903e-07, 0.00000000e+00, 0.00000000e+00],
       [6.30111432e-06, 0.00000000e+00, 0.00000000e+00],
       [3.50757092e-05, 0.00000000e+00, 0.00000000e+00],
       [3.03579340e-05, 0.00000000e+00, 0.00000000e+00],
       [9.04516202e-07, 0.00000000e+00, 0.00000000e+00],
       [9.04516202e-07, 0.00000000e+00, 0.00000000e+00],
       [9.04516202e-07, 0.00000000e+00, 0.00000000e+00],
       [9.04516202e-07, 0.00000000e+00, 0.00000000e+00],
       [9.04516202e-07, 0.00000000e+00, 0.00000000e+00],
       [9.04516202e-07, 0.00000000e+00, 0.00000000e+00],
       [9.04516202e-07, 0.00000000e+00, 0.00000000e+00],
       [9.04516202e-07, 0.00000000e+00, 0.00000000e+00],
       [9.04516202e-07, 0.00000000e+00, 0.00000000e+00],
       [9.04516202e-07, 0.00000000e+00, 0.00000000e+00],
       [9.04516202e-07, 0.00000000e+00, 0.00000000e+00],
       [9.04516202e-07, 0.00000000e+00, 0.00000000e+00],
       [9.04516202e-07, 0.00000000e+00, 0.00000000e+00],
       [9.04516202e-07, 0.00000000e+00, 0.00000000e+00],
       [9.04516202e-07, 0.00000000e+00, 0.00000000e+00],
       [9.04516202e-07, 0.00000000e+00, 0.00000000e+00],
       [9.04516202e-07, 0.00000000e+00, 0.00000000e+00],
       [9.04516202e-07, 0.00000000e+00, 0.00000000e+00],
       [2.43295688e-06, 0.00000000e+00, 0.00000000e+00],
       [2.43295688e-06, 0.00000000e+00, 0.00000000e+00],
       [2.43295688e-06, 0.00000000e+00, 0.00000000e+00],
       [2.43295688e-06, 0.00000000e+00, 0.00000000e+00],
       [4.47979513e-05, 0.00000000e+00, 0.00000000e+00],
       [2.46720301e-05, 0.00000000e+00, 0.00000000e+00],
       [4.91767508e-05, 0.00000000e+00, 0.00000000e+00],
       [2.05110813e-05, 0.00000000e+00, 0.00000000e+00],
       [5.14702832e-05, 0.00000000e+00, 0.00000000e+00],
       [1.60137710e-05, 0.00000000e+00, 0.00000000e+00],
       [1.60137710e-05, 0.00000000e+00, 0.00000000e+00],
       [1.60137710e-05, 0.00000000e+00, 0.00000000e+00],
       [1.60137710e-05, 0.00000000e+00, 0.00000000e+00],
       [1.60137710e-05, 0.00000000e+00, 0.00000000e+00],
       [1.28235650e-05, 0.00000000e+00, 0.00000000e+00],
       [1.28235650e-05, 0.00000000e+00, 0.00000000e+00],
       [1.28235650e-05, 0.00000000e+00, 0.00000000e+00],
       [1.28235650e-05, 0.00000000e+00, 0.00000000e+00],
       [1.28235650e-05, 0.00000000e+00, 0.00000000e+00],
       [5.00629676e-05, 0.00000000e+00, 0.00000000e+00],
       [4.54828740e-05, 0.00000000e+00, 0.00000000e+00],
       [2.86691552e-06, 0.00000000e+00, 0.00000000e+00],
       [2.86691552e-06, 0.00000000e+00, 0.00000000e+00],
       [2.86691552e-06, 0.00000000e+00, 0.00000000e+00],
       [2.86691552e-06, 0.00000000e+00, 0.00000000e+00],
       [2.86691552e-06, 0.00000000e+00, 0.00000000e+00],
       [2.86691552e-06, 0.00000000e+00, 0.00000000e+00],
       [3.70215519e-05, 0.00000000e+00, 0.00000000e+00],
       [4.19092507e-05, 0.00000000e+00, 0.00000000e+00],
       [4.83262616e-05, 0.00000000e+00, 0.00000000e+00],
       [5.08637868e-05, 0.00000000e+00, 0.00000000e+00],
       [4.47465385e-05, 0.00000000e+00, 0.00000000e+00],
       [4.99766987e-05, 0.00000000e+00, 0.00000000e+00],
       [5.11374073e-05, 0.00000000e+00, 0.00000000e+00],
       [1.73757737e-06, 0.00000000e+00, 0.00000000e+00],
       [1.73757737e-06, 0.00000000e+00, 0.00000000e+00],
       [1.73757737e-06, 0.00000000e+00, 0.00000000e+00],
       [1.73757737e-06, 0.00000000e+00, 0.00000000e+00],
       [1.73757737e-06, 0.00000000e+00, 0.00000000e+00],
       [1.73757737e-06, 0.00000000e+00, 0.00000000e+00],
       [1.73757737e-06, 0.00000000e+00, 0.00000000e+00],
       [1.73757737e-06, 0.00000000e+00, 0.00000000e+00],
       [3.92932992e-05, 0.00000000e+00, 0.00000000e+00],
       [1.01806000e-05, 0.00000000e+00, 0.00000000e+00],
       [1.01806000e-05, 0.00000000e+00, 0.00000000e+00],
       [1.01806000e-05, 0.00000000e+00, 0.00000000e+00],
       [1.01806000e-05, 0.00000000e+00, 0.00000000e+00],
       [1.01806000e-05, 0.00000000e+00, 0.00000000e+00],
       [1.01806000e-05, 0.00000000e+00, 0.00000000e+00],
       [1.01806000e-05, 0.00000000e+00, 0.00000000e+00],
       [1.01806000e-05, 0.00000000e+00, 0.00000000e+00],
       [4.54889738e-05, 0.00000000e+00, 0.00000000e+00],
       [3.81848747e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [1.33254930e-05, 0.00000000e+00, 0.00000000e+00],
       [5.12114766e-05, 0.00000000e+00, 0.00000000e+00],
       [4.39004063e-05, 0.00000000e+00, 0.00000000e+00],
       [2.36673026e-05, 0.00000000e+00, 0.00000000e+00],
       [8.79071238e-06, 0.00000000e+00, 0.00000000e+00],
       [8.79071238e-06, 0.00000000e+00, 0.00000000e+00],
       [8.79071238e-06, 0.00000000e+00, 0.00000000e+00],
       [8.79071238e-06, 0.00000000e+00, 0.00000000e+00],
       [8.79071238e-06, 0.00000000e+00, 0.00000000e+00],
       [8.79071238e-06, 0.00000000e+00, 0.00000000e+00],
       [5.02154631e-05, 0.00000000e+00, 0.00000000e+00],
       [4.58174927e-05, 0.00000000e+00, 0.00000000e+00],
       [2.17632872e-05, 0.00000000e+00, 0.00000000e+00],
       [4.66400970e-05, 0.00000000e+00, 0.00000000e+00],
       [2.50127486e-05, 0.00000000e+00, 0.00000000e+00],
       [4.62314091e-05, 0.00000000e+00, 0.00000000e+00],
       [3.60142101e-05, 0.00000000e+00, 0.00000000e+00],
       [4.74287166e-05, 0.00000000e+00, 0.00000000e+00],
       [4.85449837e-05, 0.00000000e+00, 0.00000000e+00],
       [5.05544388e-05, 0.00000000e+00, 0.00000000e+00],
       [3.74929808e-05, 0.00000000e+00, 0.00000000e+00],
       [1.01135020e-05, 0.00000000e+00, 0.00000000e+00],
       [1.01135020e-05, 0.00000000e+00, 0.00000000e+00],
       [1.01135020e-05, 0.00000000e+00, 0.00000000e+00],
       [1.01135020e-05, 0.00000000e+00, 0.00000000e+00],
       [1.01135020e-05, 0.00000000e+00, 0.00000000e+00],
       [1.01135020e-05, 0.00000000e+00, 0.00000000e+00],
       [1.12672394e-05, 0.00000000e+00, 0.00000000e+00],
       [4.89545431e-05, 0.00000000e+00, 0.00000000e+00],
       [5.03418165e-05, 0.00000000e+00, 0.00000000e+00],
       [2.45735616e-06, 0.00000000e+00, 0.00000000e+00],
       [2.45735616e-06, 0.00000000e+00, 0.00000000e+00],
       [2.45735616e-06, 0.00000000e+00, 0.00000000e+00],
       [2.45735616e-06, 0.00000000e+00, 0.00000000e+00],
       [2.45735616e-06, 0.00000000e+00, 0.00000000e+00],
       [2.45735616e-06, 0.00000000e+00, 0.00000000e+00],
       [2.45735616e-06, 0.00000000e+00, 0.00000000e+00],
       [5.19870252e-05, 0.00000000e+00, 0.00000000e+00],
       [4.91131384e-05, 0.00000000e+00, 0.00000000e+00],
       [5.11138795e-05, 0.00000000e+00, 0.00000000e+00],
       [1.37306954e-05, 0.00000000e+00, 0.00000000e+00],
       [1.37306954e-05, 0.00000000e+00, 0.00000000e+00],
       [1.37306954e-05, 0.00000000e+00, 0.00000000e+00],
       [1.37306954e-05, 0.00000000e+00, 0.00000000e+00],
       [4.71690386e-05, 0.00000000e+00, 0.00000000e+00],
       [4.65790988e-05, 0.00000000e+00, 0.00000000e+00],
       [4.36337570e-05, 0.00000000e+00, 0.00000000e+00],
       [3.63296580e-05, 0.00000000e+00, 0.00000000e+00],
       [3.95590771e-05, 0.00000000e+00, 0.00000000e+00],
       [4.68257058e-05, 0.00000000e+00, 0.00000000e+00],
       [3.86911598e-05, 0.00000000e+00, 0.00000000e+00],
       [3.92253298e-05, 0.00000000e+00, 0.00000000e+00],
       [4.30734450e-05, 0.00000000e+00, 0.00000000e+00],
       [4.59569171e-05, 0.00000000e+00, 0.00000000e+00],
       [4.04017237e-05, 0.00000000e+00, 0.00000000e+00],
       [1.09692196e-05, 0.00000000e+00, 0.00000000e+00],
       [4.34891042e-05, 0.00000000e+00, 0.00000000e+00],
       [4.98529595e-06, 0.00000000e+00, 0.00000000e+00],
       [1.71126100e-05, 0.00000000e+00, 0.00000000e+00],
       [1.71126100e-05, 0.00000000e+00, 0.00000000e+00],
       [1.71126100e-05, 0.00000000e+00, 0.00000000e+00],
       [1.71126100e-05, 0.00000000e+00, 0.00000000e+00],
       [4.22142417e-05, 0.00000000e+00, 0.00000000e+00],
       [3.52133909e-05, 0.00000000e+00, 0.00000000e+00],
       [4.56963677e-05, 0.00000000e+00, 0.00000000e+00],
       [4.34586051e-05, 0.00000000e+00, 0.00000000e+00],
       [2.47164716e-05, 0.00000000e+00, 0.00000000e+00],
       [8.92752263e-06, 0.00000000e+00, 0.00000000e+00],
       [8.92752263e-06, 0.00000000e+00, 0.00000000e+00],
       [8.92752263e-06, 0.00000000e+00, 0.00000000e+00],
       [8.92752263e-06, 0.00000000e+00, 0.00000000e+00],
       [8.92752263e-06, 0.00000000e+00, 0.00000000e+00],
       [8.92752263e-06, 0.00000000e+00, 0.00000000e+00],
       [8.92752263e-06, 0.00000000e+00, 0.00000000e+00],
       [8.92752263e-06, 0.00000000e+00, 0.00000000e+00],
       [8.92752263e-06, 0.00000000e+00, 0.00000000e+00],
       [8.92752263e-06, 0.00000000e+00, 0.00000000e+00],
       [8.92752263e-06, 0.00000000e+00, 0.00000000e+00],
       [8.92752263e-06, 0.00000000e+00, 0.00000000e+00],
       [8.92752263e-06, 0.00000000e+00, 0.00000000e+00],
       [8.92752263e-06, 0.00000000e+00, 0.00000000e+00],
       [4.02710133e-05, 0.00000000e+00, 0.00000000e+00],
       [4.04339656e-05, 0.00000000e+00, 0.00000000e+00],
       [4.58758767e-05, 0.00000000e+00, 0.00000000e+00],
       [2.51678583e-05, 0.00000000e+00, 0.00000000e+00],
       [9.57410358e-06, 0.00000000e+00, 0.00000000e+00],
       [9.57410358e-06, 0.00000000e+00, 0.00000000e+00],
       [9.57410358e-06, 0.00000000e+00, 0.00000000e+00],
       [9.57410358e-06, 0.00000000e+00, 0.00000000e+00],
       [9.57410358e-06, 0.00000000e+00, 0.00000000e+00],
       [9.57410358e-06, 0.00000000e+00, 0.00000000e+00],
       [9.57410358e-06, 0.00000000e+00, 0.00000000e+00],
       [9.57410358e-06, 0.00000000e+00, 0.00000000e+00],
       [9.57410358e-06, 0.00000000e+00, 0.00000000e+00],
       [9.57410358e-06, 0.00000000e+00, 0.00000000e+00],
       [9.57410358e-06, 0.00000000e+00, 0.00000000e+00],
       [4.65024154e-05, 0.00000000e+00, 0.00000000e+00],
       [3.81282336e-05, 0.00000000e+00, 0.00000000e+00],
       [3.67557740e-05, 0.00000000e+00, 0.00000000e+00],
       [4.27954675e-05, 0.00000000e+00, 0.00000000e+00],
       [4.96307517e-05, 0.00000000e+00, 0.00000000e+00],
       [4.43962346e-05, 0.00000000e+00, 0.00000000e+00],
       [3.81517614e-05, 0.00000000e+00, 0.00000000e+00],
       [1.65322557e-05, 0.00000000e+00, 0.00000000e+00],
       [1.65322557e-05, 0.00000000e+00, 0.00000000e+00],
       [1.65322557e-05, 0.00000000e+00, 0.00000000e+00],
       [1.65322557e-05, 0.00000000e+00, 0.00000000e+00],
       [1.65322557e-05, 0.00000000e+00, 0.00000000e+00],
       [1.65322557e-05, 0.00000000e+00, 0.00000000e+00],
       [1.65322557e-05, 0.00000000e+00, 0.00000000e+00],
       [1.65322557e-05, 0.00000000e+00, 0.00000000e+00],
       [1.65322557e-05, 0.00000000e+00, 0.00000000e+00],
       [4.26621428e-05, 0.00000000e+00, 0.00000000e+00],
       [4.79123452e-05, 0.00000000e+00, 0.00000000e+00],
       [4.12809692e-05, 0.00000000e+00, 0.00000000e+00],
       [1.64085165e-06, 0.00000000e+00, 0.00000000e+00],
       [1.64085165e-06, 0.00000000e+00, 0.00000000e+00],
       [1.64085165e-06, 0.00000000e+00, 0.00000000e+00],
       [1.64085165e-06, 0.00000000e+00, 0.00000000e+00],
       [1.64085165e-06, 0.00000000e+00, 0.00000000e+00],
       [1.64085165e-06, 0.00000000e+00, 0.00000000e+00],
       [1.64085165e-06, 0.00000000e+00, 0.00000000e+00],
       [1.64085165e-06, 0.00000000e+00, 0.00000000e+00],
       [1.27294535e-05, 0.00000000e+00, 0.00000000e+00],
       [1.27294535e-05, 0.00000000e+00, 0.00000000e+00],
       [1.27294535e-05, 0.00000000e+00, 0.00000000e+00],
       [1.27294535e-05, 0.00000000e+00, 0.00000000e+00],
       [1.27294535e-05, 0.00000000e+00, 0.00000000e+00],
       [1.27294535e-05, 0.00000000e+00, 0.00000000e+00],
       [1.27294535e-05, 0.00000000e+00, 0.00000000e+00],
       [1.27294535e-05, 0.00000000e+00, 0.00000000e+00],
       [1.27294535e-05, 0.00000000e+00, 0.00000000e+00],
       [3.83295276e-05, 0.00000000e+00, 0.00000000e+00],
       [3.71609763e-05, 0.00000000e+00, 0.00000000e+00],
       [4.71141402e-05, 0.00000000e+00, 0.00000000e+00],
       [4.07441850e-05, 0.00000000e+00, 0.00000000e+00],
       [1.15914013e-05, 0.00000000e+00, 0.00000000e+00],
       [1.15914013e-05, 0.00000000e+00, 0.00000000e+00],
       [1.15914013e-05, 0.00000000e+00, 0.00000000e+00],
       [1.15914013e-05, 0.00000000e+00, 0.00000000e+00],
       [1.15914013e-05, 0.00000000e+00, 0.00000000e+00],
       [1.15914013e-05, 0.00000000e+00, 0.00000000e+00],
       [1.15914013e-05, 0.00000000e+00, 0.00000000e+00],
       [1.15914013e-05, 0.00000000e+00, 0.00000000e+00],
       [1.15914013e-05, 0.00000000e+00, 0.00000000e+00],
       [4.87863623e-05, 0.00000000e+00, 0.00000000e+00],
       [5.18885566e-05, 0.00000000e+00, 0.00000000e+00],
       [4.18935655e-05, 0.00000000e+00, 0.00000000e+00]])

In [32]:
x = accs_t_0[['INIT_BALANCE', 'TX_BEHAVIOR_ID']].values

In [33]:
x

array([[0.05197702, 0.        ],
       [0.06089769, 0.        ],
       [0.056578  , 0.        ],
       [0.05028932, 0.        ],
       [0.24134051, 0.25      ],
       [0.37533151, 0.25      ],
       [0.58928715, 0.25      ],
       [0.52437113, 0.25      ],
       [0.53232741, 0.25      ],
       [0.8010528 , 0.5       ],
       [0.9513381 , 0.5       ],
       [0.95248332, 0.5       ],
       [0.67947842, 0.5       ],
       [0.83074821, 0.5       ],
       [0.99150125, 0.5       ],
       [0.9254601 , 0.5       ],
       [0.78270915, 0.5       ],
       [0.7313148 , 0.5       ],
       [0.97755766, 0.5       ],
       [0.64652817, 0.5       ],
       [0.886623  , 0.5       ],
       [0.82269147, 0.5       ],
       [0.19360283, 0.75      ],
       [0.11562726, 0.75      ],
       [0.05828578, 0.75      ],
       [0.03801334, 0.75      ],
       [0.17612312, 0.75      ],
       [0.18548582, 0.75      ],
       [0.1692317 , 0.75      ],
       [0.52702323, 1.        ],
       [0.0234871 , 0.        ],
       [0.34961424, 0.25      ],
       [0.20957567, 0.25      ],
       [0.21003777, 0.25      ],
       [0.30531222, 0.25      ],
       [0.80509122, 0.5       ],
       [0.61854054, 0.5       ],
       [0.64325323, 0.5       ],
       [0.99981918, 0.5       ],
       [0.68281363, 0.5       ],
       [0.93958451, 0.5       ],
       [0.97179137, 0.5       ],
       [0.67077875, 0.5       ],
       [0.99109941, 0.5       ],
       [0.87442739, 0.5       ],
       [0.70344772, 0.5       ],
       [0.67294865, 0.5       ],
       [0.09471189, 0.75      ],
       [0.06252511, 0.75      ],
       [0.07172708, 0.75      ],
       [0.1682673 , 0.75      ],
       [0.11259343, 0.75      ],
       [0.45553725, 1.        ],
       [0.29707466, 1.        ],
       [0.45700394, 1.        ],
       [0.55264004, 1.        ],
       [0.48290203, 1.        ],
       [0.36894238, 1.        ],
       [0.46696938, 1.        ],
       [0.17754963, 0.        ],
       [0.162501  , 0.        ],
       [0.36233223, 0.25      ],
       [0.2018203 , 0.25      ],
       [0.46176565, 0.25      ],
       [0.23356506, 0.25      ],
       [0.74216427, 0.5       ],
       [0.71457848, 0.5       ],
       [0.98304267, 0.5       ],
       [0.97980792, 0.5       ],
       [0.61958531, 0.5       ],
       [0.90374106, 0.5       ],
       [0.88451338, 0.5       ],
       [0.86604918, 0.5       ],
       [0.88895363, 0.5       ],
       [0.1179177 , 0.75      ],
       [0.00174797, 0.75      ],
       [0.06792976, 0.75      ],
       [0.00823756, 0.75      ],
       [0.19723941, 0.75      ],
       [0.36287471, 1.        ],
       [0.33287792, 1.        ],
       [0.39339388, 1.        ],
       [0.32218918, 1.        ],
       [0.19577272, 0.        ],
       [0.09007072, 0.        ],
       [0.30571406, 0.25      ],
       [0.22653299, 0.25      ],
       [0.24865386, 0.25      ],
       [0.42043719, 0.25      ],
       [0.66352568, 0.5       ],
       [0.99770956, 0.5       ],
       [0.66234027, 0.5       ],
       [0.8017761 , 0.5       ],
       [0.87195612, 0.5       ],
       [0.84772563, 0.5       ],
       [0.98949208, 0.5       ],
       [0.9314474 , 0.5       ],
       [0.02977578, 0.75      ],
       [0.16211926, 0.75      ],
       [0.03224705, 0.75      ],
       [0.40277666, 1.        ],
       [0.52439122, 1.        ],
       [0.43651049, 1.        ],
       [0.10180423, 0.        ],
       [0.06079724, 0.        ],
       [0.16270192, 0.        ],
       [0.59736398, 0.25      ],
       [0.44669694, 0.25      ],
       [0.26169332, 0.25      ],
       [0.24318894, 0.25      ],
       [0.42154223, 0.25      ],
       [0.79972675, 0.5       ],
       [0.95684321, 0.5       ],
       [0.84786627, 0.5       ],
       [0.85678695, 0.5       ],
       [0.73846741, 0.5       ],
       [0.65265611, 0.5       ],
       [0.87697902, 0.5       ],
       [0.85266817, 0.5       ],
       [0.65378124, 0.5       ],
       [0.92391304, 0.5       ],
       [0.95332717, 0.5       ],
       [0.87635618, 0.5       ],
       [0.92829302, 0.5       ],
       [0.81125934, 0.5       ],
       [0.91834767, 0.5       ],
       [0.67871494, 0.5       ],
       [0.08928715, 0.75      ],
       [0.32355541, 1.        ],
       [0.36789761, 1.        ],
       [0.38037451, 1.        ],
       [0.58753918, 1.        ],
       [0.49121996, 1.        ],
       [0.06985856, 0.        ],
       [0.19571245, 0.        ],
       [0.04175038, 0.        ],
       [0.5862935 , 0.25      ],
       [0.43428032, 0.25      ],
       [0.71966166, 0.5       ],
       [0.65585068, 0.5       ],
       [0.610966  , 0.5       ],
       [0.63401109, 0.5       ],
       [0.63212248, 0.5       ],
       [0.90042594, 0.5       ],
       [0.65988909, 0.5       ],
       [0.77236197, 0.5       ],
       [0.85865547, 0.5       ],
       [0.63668328, 0.5       ],
       [0.62595435, 0.5       ],
       [0.76691714, 0.5       ],
       [0.06439363, 0.75      ],
       [0.05888853, 0.75      ],
       [0.09457124, 0.75      ],
       [0.08960862, 0.75      ],
       [0.08008519, 0.75      ],
       [0.45696375, 1.        ],
       [0.20161938, 1.        ],
       [0.41995499, 1.        ],
       [0.48469019, 1.        ],
       [0.4733987 , 1.        ],
       [0.07956281, 0.        ],
       [0.18255244, 0.        ],
       [0.11958531, 0.        ],
       [0.0613598 , 0.        ],
       [0.36757615, 0.25      ],
       [0.45587881, 0.25      ],
       [0.3183115 , 0.25      ],
       [0.45354818, 0.25      ],
       [0.87123282, 0.5       ],
       [0.7449771 , 0.5       ],
       [0.7305915 , 0.5       ],
       [0.90215382, 0.5       ],
       [0.7921924 , 0.5       ],
       [0.95975649, 0.5       ],
       [0.81441373, 0.5       ],
       [0.62941011, 0.5       ],
       [0.95113719, 0.5       ],
       [0.13784859, 0.75      ],
       [0.13437274, 0.75      ],
       [0.12470867, 0.75      ],
       [0.14604597, 0.75      ],
       [0.09256208, 0.75      ],
       [0.06630234, 0.75      ],
       [0.03377401, 0.75      ],
       [0.18022181, 0.75      ],
       [0.48571486, 1.        ],
       [0.56670417, 1.        ],
       [0.37932974, 1.        ],
       [0.52509443, 1.        ],
       [0.5786185 , 1.        ],
       [0.43657076, 1.        ],
       [0.27591819, 1.        ],
       [0.14158563, 0.        ],
       [0.07090332, 0.        ],
       [0.0920397 , 0.        ],
       [0.04323716, 0.        ],
       [0.30770313, 0.25      ],
       [0.25729326, 0.25      ],
       [0.47432291, 0.25      ],
       [0.36020252, 0.25      ],
       [0.57112433, 0.25      ],
       [0.33729808, 0.25      ],
       [0.55563369, 0.25      ],
       [0.52025235, 0.25      ],
       [0.33153178, 0.25      ],
       [0.21246886, 0.25      ],
       [0.62052962, 0.5       ],
       [0.75086394, 0.5       ],
       [0.68693241, 0.5       ],
       [0.67817247, 0.5       ],
       [0.87300088, 0.5       ],
       [0.94828418, 0.5       ],
       [0.70503496, 0.5       ],
       [0.74091859, 0.5       ],
       [0.8890139 , 0.5       ],
       [0.97810014, 0.5       ],
       [0.78793297, 0.5       ],
       [0.92779073, 0.5       ],
       [0.09248172, 0.75      ],
       [0.01979024, 0.75      ],
       [0.15374106, 0.75      ],
       [0.00787591, 0.75      ],
       [0.02569718, 0.75      ],
       [0.37561279, 1.        ],
       [0.41830748, 1.        ],
       [0.24061721, 1.        ],
       [0.30083179, 1.        ],
       [0.49899542, 1.        ],
       [0.17256691, 0.        ],
       [0.12959093, 0.        ],
       [0.14130435, 0.        ],
       [0.13268504, 0.        ],
       [0.04448284, 0.        ],
       [0.10407458, 0.        ],
       [0.05758258, 0.        ],
       [0.16264165, 0.        ],
       [0.33263682, 0.25      ],
       [0.43612875, 0.25      ],
       [0.21104235, 0.25      ],
       [0.50829784, 0.25      ],
       [0.52883147, 0.25      ],
       [0.43837901, 0.25      ],
       [0.8554609 , 0.5       ],
       [0.96467894, 0.5       ],
       [0.93781644, 0.5       ],
       [0.78578317, 0.5       ],
       [0.60779153, 0.5       ],
       [0.69113156, 0.5       ],
       [0.86500442, 0.5       ],
       [0.80149482, 0.5       ],
       [0.98579523, 0.5       ],
       [0.72886362, 0.5       ],
       [0.94338182, 0.5       ],
       [0.70684321, 0.5       ],
       [0.88535723, 0.5       ],
       [0.932894  , 0.5       ],
       [0.07713172, 0.75      ],
       [0.01185405, 0.75      ],
       [0.00765491, 0.75      ],
       [0.14592542, 0.75      ],
       [0.1931809 , 0.75      ],
       [0.06891425, 0.75      ],
       [0.13212248, 0.75      ],
       [0.06121916, 0.75      ],
       [0.07156634, 0.75      ],
       [0.00490235, 0.75      ],
       [0.22761794, 1.        ],
       [0.2878727 , 1.        ],
       [0.37575344, 1.        ],
       [0.34475207, 1.        ],
       [0.27198023, 1.        ],
       [0.33299847, 1.        ],
       [0.59740416, 1.        ],
       [0.50116531, 1.        ],
       [0.35463715, 1.        ],
       [0.49648397, 1.        ],
       [0.13790886, 0.        ],
       [0.09290364, 0.        ],
       [0.08211444, 0.        ],
       [0.0783774 , 0.        ],
       [0.02772643, 0.        ],
       [0.17453588, 0.        ],
       [0.06628225, 0.        ],
       [0.1687495 , 0.        ],
       [0.03387447, 0.        ],
       [0.15822149, 0.        ],
       [0.26850438, 0.25      ],
       [0.44113156, 0.25      ],
       [0.30231857, 0.25      ],
       [0.21182593, 0.25      ],
       [0.31851242, 0.25      ],
       [0.26147231, 0.25      ],
       [0.29576871, 0.25      ],
       [0.34384795, 0.25      ],
       [0.89825605, 0.5       ],
       [0.7653299 , 0.5       ],
       [0.71114281, 0.5       ],
       [0.76046773, 0.5       ],
       [0.72757775, 0.5       ],
       [0.9954392 , 0.5       ],
       [0.91328458, 0.5       ],
       [0.83195371, 0.5       ],
       [0.70816925, 0.5       ],
       [0.8787069 , 0.5       ],
       [0.78590372, 0.5       ],
       [0.89259021, 0.5       ],
       [0.76496826, 0.5       ],
       [0.61102628, 0.5       ],
       [0.61647111, 0.5       ],
       [0.13672346, 0.75      ],
       [0.11689303, 0.75      ],
       [0.15585068, 0.75      ],
       [0.05818533, 0.75      ],
       [0.04156956, 0.75      ],
       [0.10630475, 0.75      ],
       [0.06833159, 0.75      ],
       [0.19523025, 0.75      ],
       [0.06614161, 0.75      ],
       [0.18570682, 0.75      ],
       [0.11771679, 0.75      ],
       [0.14463956, 0.75      ],
       [0.07096359, 0.75      ],
       [0.56230411, 1.        ],
       [0.33374186, 1.        ],
       [0.20453267, 1.        ],
       [0.52891184, 1.        ],
       [0.427851  , 1.        ],
       [0.4523025 , 1.        ],
       [0.33066785, 1.        ],
       [0.51543036, 1.        ],
       [0.44225669, 1.        ],
       [0.59766535, 1.        ],
       [0.20127783, 1.        ],
       [0.21839589, 1.        ],
       [0.2514466 , 1.        ],
       [0.57433899, 1.        ],
       [0.58205417, 1.        ],
       [0.39391626, 1.        ]])

In [34]:
y = transactions_t0['IS_FRAUD']

In [35]:
y = y.apply(lambda v: 1 if v else 0)

In [36]:
y.values

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
import torch
from torch_geometric.data import Data


def get_converted_index(old, acc_list):
    return acc_list.index(old)


graphs = []

for timestamp in range(200):
    timestamp_transacs = transactions[transactions.TIMESTAMP == timestamp]
    t_sender_accs = timestamp_transacs.SENDER_ACCOUNT_ID.values.tolist()
    t_receiver_accs = timestamp_transacs.RECEIVER_ACCOUNT_ID.values.tolist()
    timestamp_accs = list(set(t_sender_accs + t_receiver_accs))
    timestamp_accs.sort()
    t_accs_features = account_list.loc[timestamp_accs].reset_index()\
        .reset_index()[['level_0', 'index' ,'INIT_BALANCE', 'TX_BEHAVIOR_ID']]
    t_accs_features
    timestamp_transacs.SENDER_ACCOUNT_ID = timestamp_transacs.SENDER_ACCOUNT_ID\
        .apply(lambda line: get_converted_index(line, timestamp_accs))
    timestamp_transacs.RECEIVER_ACCOUNT_ID = timestamp_transacs.RECEIVER_ACCOUNT_ID\
        .apply(lambda line: get_converted_index(line, timestamp_accs))
    edge_index = torch.tensor(timestamp_transacs[['SENDER_ACCOUNT_ID', 'RECEIVER_ACCOUNT_ID']].values.T)
    edge_attr = torch.tensor(timestamp_transacs[['TX_AMOUNT', 'TIMESTAMP', 'ALERT_ID']].values.T)
    y = torch.tensor(timestamp_transacs['IS_FRAUD'].apply(lambda v: 1 if v else 0).values)
    x = torch.tensor(t_accs_features[['INIT_BALANCE', 'TX_BEHAVIOR_ID']].values.T)
    edge_to_edge_adj_matr = torch.zeros([edge_attr.T.shape[0], edge_attr.T.shape[0]])
    edge_to_node_adj_matr = torch.zeros([edge_attr.T.shape[0], x.T.shape[0]])                                                         
    node_to_edge_adj_matr = torch.zeros([x.T.shape[0], edge_attr.T.shape[0]])
    node_to_node_adj_matr = torch.zeros([x.T.shape[0], x.T.shape[0]])
    for n, ei in enumerate(edge_index):
        node_to_node_adj_matr[ei[0]][ei[1]] = 1.0
        node_to_edge_adj_matr[ei[0]][n] = 1.0
        node_to_edge_adj_matr[ei[1]][n] = 1.0
        edge_to_node_adj_matr[n][ei[1]] = 1.0
        edge_to_node_adj_matr[n][ei[0]] = 1.0
    
    for n, ei in enumerate(edge_index):
        for n2, e2 in enumerate(edge_to_node_adj_matr[:, ei[0]]):
            if e2 == 1.0:
                edge_to_edge_adj_matr[n2][n] = 1.0
    data = Data(
        x=x,
        y=y,
        edge_attr=edge_attr,
        edge_index=edge_index,
        node_to_node_adj_matr=node_to_node_adj_matr,
        node_to_edge_adj_matr=node_to_edge_adj_matr,
        edge_to_node_adj_matr=edge_to_node_adj_matr,
        edge_to_edge_adj_matr=edge_to_edge_adj_matr
    )
    graphs.append(data)

/tmp/ipykernel_2286/3041386631.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  timestamp_transacs.SENDER_ACCOUNT_ID = timestamp_transacs.SENDER_ACCOUNT_ID\
/tmp/ipykernel_2286/3041386631.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  timestamp_transacs.RECEIVER_ACCOUNT_ID = timestamp_transacs.RECEIVER_ACCOUNT_ID\
/tmp/ipykernel_2286/3041386631.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  timestamp_transacs.SENDER_ACCOUNT_ID = timestamp_transacs.SENDER_ACCOUNT_ID\
/tmp/ipykernel_2286/3041386631.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  timestamp_transacs.RECEIVER_ACCOUNT_ID = timestamp_transacs.RECEIVER_ACCOUNT_ID\

IndexError: index 0 is out of bounds for dimension 0 with size 0

In [ ]:
import os

NAME_DIR = '1Kvertices-100Kedges_pt/'

if not os.path.exists(NAME_DIR):
    os.mkdir(NAME_DIR)

NAME_DIR = '1Kvertices-100Kedges_pt/'

for i, g in enumerate(graphs):
    name_out = NAME_DIR + str(i) + '.pt'
    torch.save(g, name_out)