In [1]:
import pandas as pd
path = 'dataset/raw/'

elliptic_txs_classes = pd.read_csv(path + 'elliptic_txs_classes.csv')
elliptic_txs_edgelist = pd.read_csv(path + 'elliptic_txs_edgelist.csv')
elliptic_txs_features = pd.read_csv(path + 'elliptic_txs_features.csv', header = None)

In [2]:
filter = [elliptic_txs_classes != 'unknown']

In [3]:
filter = filter[0]['class']

In [4]:
elliptic_txs_classes[filter]

             txId class
3       232438397     2
9       232029206     2
10      232344069     2
11       27553029     2
16        3881097     2
...           ...   ...
203752   80329479     2
203754  158406298     2
203759  158375075     1
203763  147478192     2
203766  158375402     1

[46564 rows x 2 columns]

In [5]:
elliptic_txs_features

,0,1,2,3,4,5,6,7,8,9,...,157,158,159,160,161,162,163,164,165,166
0,230425980,1,-0.171469,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.162097,...,-0.562153,-0.600999,1.461330,1.461369,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792
1,5530458,1,-0.171484,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.162112,...,0.947382,0.673103,-0.979074,-0.978556,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792
2,232022460,1,-0.172107,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.162749,...,0.670883,0.439728,-0.979074,-0.978556,-0.098889,-0.106715,-0.131155,-0.183671,-0.120613,-0.119792
3,232438397,1,0.163054,1.963790,-0.646376,12.409294,-0.063725,9.782742,12.414558,-0.163645,...,-0.577099,-0.613614,0.241128,0.241406,1.072793,0.085530,-0.131155,0.677799,-0.120613,-0.119792
4,230460314,1,1.011523,-0.081127,-1.201369,1.153668,0.333276,1.312656,-0.061584,-0.163523,...,-0.511871,-0.400422,0.517257,0.579382,0.018279,0.277775,0.326394,1.293750,0.178136,0.179117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203764,173077460,49,-0.145771,-0.163752,0.463609,-0.121970,-0.043875,-0.113002,-0.061584,-0.135803,...,-0.577099,-0.613614,0.241128,0.241406,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792
203765,158577750,49,-0.165920,-0.123607,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,-0.156418,...,0.162722,0.010822,1.461330,1.461369,-0.098889,-0.087490,-0.084674,-0.140597,-1.760926,-1.760984
203766,158375402,49,-0.172014,-0.078182,1.018602,0.028105,-0.043875,0.054722,-0.061584,-0.163626,...,1.261246,1.985050,1.461330,1.461369,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792
203767,158654197,49,-0.172842,-0.176622,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,-0.163501,...,-0.397749,-0.411776,1.461330,1.461369,-0.098889,-0.087490,-0.084674,-0.140597,1.519700,1.521399
203768,157597225,49,-0.012037,-0.132276,0.463609,-0.121970,-0.043875,-0.113002,-0.061584,0.001027,...,-0.577099,-0.613614,0.241128,0.241406,-0.098889,-0.087490,-0.084674,-0.140597,1.519700,1.521399

In [6]:
elliptic_txs_features[filter & (elliptic_txs_features[1] >= 36)]

,0,1,2,3,4,5,6,7,8,9,...,157,158,159,160,161,162,163,164,165,166
141774,200459281,36,-0.172879,-0.058452,0.463609,-0.121970,-0.043875,-0.113002,-0.061584,-0.163536,...,2.262621,1.947206,1.461330,1.461369,-0.098889,-0.087490,-0.084674,-0.140597,-1.760926,-1.760984
141777,199944769,36,-0.172828,0.339970,1.018602,0.178180,-0.043875,0.222447,-0.061584,-0.163620,...,-0.524789,-0.531617,-0.979074,-0.978556,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792
141781,198827545,36,-0.172282,0.837998,1.018602,0.553368,-0.043875,0.641758,-0.061584,-0.163574,...,1.149152,1.070472,1.461330,1.461369,-0.098889,-0.087490,-0.084674,-0.140597,-1.760926,-1.760984
141782,200997190,36,-0.172926,0.156148,1.573595,-0.046932,-0.043875,-0.029140,-0.061584,-0.163636,...,0.125358,0.080204,1.461330,1.461369,0.018279,-0.049041,-0.038193,-0.011377,-1.760926,-1.760984
141783,200996856,36,-0.171396,1.311640,1.573595,0.478330,-0.004174,0.474034,-0.061584,-0.163614,...,-0.106650,-0.137402,0.258822,0.729391,0.018279,0.393121,0.680158,0.462432,0.359796,1.091185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203752,80329479,49,-0.159293,-0.037276,1.018602,-0.121970,0.035526,-0.113002,-0.061584,-0.149635,...,1.793987,1.408971,0.231244,-0.388216,-0.098889,1.931078,3.168259,3.707301,-1.390548,-1.214035
203754,158406298,49,-0.172962,-0.126566,1.018602,-0.121970,-0.063725,-0.113002,-0.061584,-0.163622,...,-0.577099,0.647874,0.241128,0.241406,10.914916,1.700384,-0.131155,7.914145,-0.120613,-0.119792
203759,158375075,49,-0.170412,-0.078164,1.018602,0.028105,-0.043875,0.054722,-0.061584,-0.163631,...,1.709623,1.606604,1.461330,1.461369,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792
203763,147478192,49,-0.093732,-0.116160,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,-0.082559,...,-0.577099,-0.613614,0.241128,0.241406,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792
203766,158375402,49,-0.172014,-0.078182,1.018602,0.028105,-0.043875,0.054722,-0.061584,-0.163626,...,1.261246,1.985050,1.461330,1.461369,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792

In [7]:
dict1 = elliptic_txs_classes[filter & (elliptic_txs_features[1] == 1)].reset_index()['txId'].T.to_dict()

In [8]:
elliptic_txs_edgelist

            txId1      txId2
0       230425980    5530458
1       232022460  232438397
2       230460314  230459870
3       230333930  230595899
4       232013274  232029206
...           ...        ...
234350  158365409  157930723
234351  188708874  188708879
234352  157659064  157659046
234353   87414554  106877725
234354  158589452  158589457

[234355 rows x 2 columns]

In [9]:
def feedEdgeList(row):
    row['classv1'] = elliptic_txs_classes[elliptic_txs_classes['txId'] == row['txId1']]['class'].values[0]
    row['classv2'] = elliptic_txs_classes[elliptic_txs_classes['txId'] == row['txId2']]['class'].values[0]
    row['graph'] = elliptic_txs_features[elliptic_txs_features[0] == row['txId1']][1].values[0]
    return row

elliptic_txs_edgelist = elliptic_txs_edgelist.apply(feedEdgeList, axis=1)

In [10]:
elliptic_txs_edgelist

            txId1      txId2  classv1  classv2  graph
0       230425980    5530458  unknown  unknown      1
1       232022460  232438397  unknown        2      1
2       230460314  230459870  unknown  unknown      1
3       230333930  230595899  unknown  unknown      1
4       232013274  232029206  unknown        2      1
...           ...        ...      ...      ...    ...
234350  158365409  157930723        1        2     49
234351  188708874  188708879  unknown  unknown     49
234352  157659064  157659046  unknown  unknown     49
234353   87414554  106877725  unknown        2     49
234354  158589452  158589457  unknown  unknown     49

[234355 rows x 5 columns]

In [12]:
import torch
from torch_geometric.data import Data

In [13]:
elliptic_txs_features

,0,1,2,3,4,5,6,7,8,9,...,157,158,159,160,161,162,163,164,165,166
0,230425980,1,-0.171469,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.162097,...,-0.562153,-0.600999,1.461330,1.461369,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792
1,5530458,1,-0.171484,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.162112,...,0.947382,0.673103,-0.979074,-0.978556,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792
2,232022460,1,-0.172107,-0.184668,-1.201369,-0.121970,-0.043875,-0.113002,-0.061584,-0.162749,...,0.670883,0.439728,-0.979074,-0.978556,-0.098889,-0.106715,-0.131155,-0.183671,-0.120613,-0.119792
3,232438397,1,0.163054,1.963790,-0.646376,12.409294,-0.063725,9.782742,12.414558,-0.163645,...,-0.577099,-0.613614,0.241128,0.241406,1.072793,0.085530,-0.131155,0.677799,-0.120613,-0.119792
4,230460314,1,1.011523,-0.081127,-1.201369,1.153668,0.333276,1.312656,-0.061584,-0.163523,...,-0.511871,-0.400422,0.517257,0.579382,0.018279,0.277775,0.326394,1.293750,0.178136,0.179117
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203764,173077460,49,-0.145771,-0.163752,0.463609,-0.121970,-0.043875,-0.113002,-0.061584,-0.135803,...,-0.577099,-0.613614,0.241128,0.241406,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792
203765,158577750,49,-0.165920,-0.123607,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,-0.156418,...,0.162722,0.010822,1.461330,1.461369,-0.098889,-0.087490,-0.084674,-0.140597,-1.760926,-1.760984
203766,158375402,49,-0.172014,-0.078182,1.018602,0.028105,-0.043875,0.054722,-0.061584,-0.163626,...,1.261246,1.985050,1.461330,1.461369,0.018279,-0.087490,-0.131155,-0.097524,-0.120613,-0.119792
203767,158654197,49,-0.172842,-0.176622,1.018602,-0.121970,-0.043875,-0.113002,-0.061584,-0.163501,...,-0.397749,-0.411776,1.461330,1.461369,-0.098889,-0.087490,-0.084674,-0.140597,1.519700,1.521399
203768,157597225,49,-0.012037,-0.132276,0.463609,-0.121970,-0.043875,-0.113002,-0.061584,0.001027,...,-0.577099,-0.613614,0.241128,0.241406,-0.098889,-0.087490,-0.084674,-0.140597,1.519700,1.521399

In [16]:
import numpy as np

def updateVerticeNumber(row, dt):
    row['txId1'] = dt[row['txId1']]
    row['txId2'] = dt[row['txId2']]
    return row

datas = []

for i in range(1, 50):
    features = elliptic_txs_features[filter & (elliptic_txs_features[1] == i)]
    classes = elliptic_txs_classes[filter & (elliptic_txs_features[1] == i)]
    index_dt = classes.reset_index()['txId'].T.to_dict()
    index_dt = {v: k for k, v in index_dt.items()}
    edgelist = elliptic_txs_edgelist[(elliptic_txs_edgelist['graph'] == i) & (elliptic_txs_edgelist['classv1'] != 'unknown') & (elliptic_txs_edgelist['classv2'] != 'unknown')]
    edgelist = edgelist.apply(lambda row: updateVerticeNumber(row, index_dt), axis=1)[['txId1', 'txId2']]
    classes = classes.astype({'class': int})
    classes['class'] = classes['class'].apply(lambda x: x-1)
    
    adjacency_matrix = np.zeros((len(classes), len(classes)))
    for i in range(len(edgelist)):
        adjacency_matrix[edgelist.reset_index().loc[i].txId1][edgelist.reset_index().loc[i].txId2] = 1
    
    adjacency_matrix = torch.tensor(adjacency_matrix)
    x = torch.tensor(features.drop(0, axis=1).values)
    y = torch.tensor(classes['class'].values)
    edgelist = torch.tensor(edgelist.T.values)
    datas.append(Data(x=x, y=y, edge_index=edgelist, adjacency_matrix=adjacency_matrix))

In [17]:
len(datas)

49

In [18]:
datas

[Data(adjacency_matrix=[2147, 2147], edge_index=[2, 1924], x=[2147, 166], y=[2147]),
 Data(adjacency_matrix=[1117, 1117], edge_index=[2, 858], x=[1117, 166], y=[1117]),
 Data(adjacency_matrix=[1279, 1279], edge_index=[2, 727], x=[1279, 166], y=[1279]),
 Data(adjacency_matrix=[1440, 1440], edge_index=[2, 1169], x=[1440, 166], y=[1440]),
 Data(adjacency_matrix=[1882, 1882], edge_index=[2, 1491], x=[1882, 166], y=[1882]),
 Data(adjacency_matrix=[485, 485], edge_index=[2, 209], x=[485, 166], y=[485]),
 Data(adjacency_matrix=[1203, 1203], edge_index=[2, 858], x=[1203, 166], y=[1203]),
 Data(adjacency_matrix=[1165, 1165], edge_index=[2, 1044], x=[1165, 166], y=[1165]),
 Data(adjacency_matrix=[778, 778], edge_index=[2, 484], x=[778, 166], y=[778]),
 Data(adjacency_matrix=[972, 972], edge_index=[2, 538], x=[972, 166], y=[972]),
 Data(adjacency_matrix=[696, 696], edge_index=[2, 477], x=[696, 166], y=[696]),
 Data(adjacency_matrix=[506, 506], edge_index=[2, 446], x=[506, 166], y=[506]),
 Data(adjacency_matrix=[809, 809], edge_index=[2, 564], x=[809, 166], y=[809]),
 Data(adjacency_matrix=[417, 417], edge_index=[2, 350], x=[417, 166], y=[417]),
 Data(adjacency_matrix=[618, 618], edge_index=[2, 446], x=[618, 166], y=[618]),
 Data(adjacency_matrix=[530, 530], edge_index=[2, 334], x=[530, 166], y=[530]),
 Data(adjacency_matrix=[811, 811], edge_index=[2, 673], x=[811, 166], y=[811]),
 Data(adjacency_matrix=[389, 389], edge_index=[2, 275], x=[389, 166], y=[389]),
 Data(adjacency_matrix=[745, 745], edge_index=[2, 585], x=[745, 166], y=[745]),
 Data(adjacency_matrix=[900, 900], edge_index=[2, 613], x=[900, 166], y=[900]),
 Data(adjacency_matrix=[641, 641], edge_index=[2, 518], x=[641, 166], y=[641]),
 Data(adjacency_matrix=[1763, 1763], edge_index=[2, 1537], x=[1763, 166], y=[1763]),
 Data(adjacency_matrix=[1187, 1187], edge_index=[2, 1046], x=[1187, 166], y=[1187]),
 Data(adjacency_matrix=[1126, 1126], edge_index=[2, 961], x=[1126, 166], y=[1126]),
 Data(adjacency_matrix=[594, 594], edge_index=[2, 559], x=[594, 166], y=[594]),
 Data(adjacency_matrix=[517, 517], edge_index=[2, 346], x=[517, 166], y=[517]),
 Data(adjacency_matrix=[206, 206], edge_index=[2, 58], x=[206, 166], y=[206]),
 Data(adjacency_matrix=[284, 284], edge_index=[2, 150], x=[284, 166], y=[284]),
 Data(adjacency_matrix=[1174, 1174], edge_index=[2, 911], x=[1174, 166], y=[1174]),
 Data(adjacency_matrix=[524, 524], edge_index=[2, 372], x=[524, 166], y=[524]),
 Data(adjacency_matrix=[710, 710], edge_index=[2, 522], x=[710, 166], y=[710]),
 Data(adjacency_matrix=[1323, 1323], edge_index=[2, 997], x=[1323, 166], y=[1323]),
 Data(adjacency_matrix=[441, 441], edge_index=[2, 429], x=[441, 166], y=[441]),
 Data(adjacency_matrix=[515, 515], edge_index=[2, 427], x=[515, 166], y=[515]),
 Data(adjacency_matrix=[1341, 1341], edge_index=[2, 1002], x=[1341, 166], y=[1341]),
 Data(adjacency_matrix=[1708, 1708], edge_index=[2, 1148], x=[1708, 166], y=[1708]),
 Data(adjacency_matrix=[498, 498], edge_index=[2, 423], x=[498, 166], y=[498]),
 Data(adjacency_matrix=[756, 756], edge_index=[2, 653], x=[756, 166], y=[756]),
 Data(adjacency_matrix=[1183, 1183], edge_index=[2, 1055], x=[1183, 166], y=[1183]),
 Data(adjacency_matrix=[1211, 1211], edge_index=[2, 1180], x=[1211, 166], y=[1211]),
 Data(adjacency_matrix=[1132, 1132], edge_index=[2, 1048], x=[1132, 166], y=[1132]),
 Data(adjacency_matrix=[2154, 2154], edge_index=[2, 1443], x=[2154, 166], y=[2154]),
 Data(adjacency_matrix=[1370, 1370], edge_index=[2, 935], x=[1370, 166], y=[1370]),
 Data(adjacency_matrix=[1591, 1591], edge_index=[2, 1497], x=[1591, 166], y=[1591]),
 Data(adjacency_matrix=[1221, 1221], edge_index=[2, 1346], x=[1221, 166], y=[1221]),
 Data(adjacency_matrix=[712, 712], edge_index=[2, 388], x=[712, 166], y=[712]),
 Data(adjacency_matrix=[846, 846], edge_index=[2, 822], x=[846, 166], y=[846]),
 Data(adjacency_matrix=[471, 471], edge_index=[2, 371], x=[471, 166], y=[471]),
 Data(adjacency_matrix=[476, 476], edge_index=[2, 415], x=[476, 166], y=[476])]

In [21]:
datas[0].adjacency_matrix.sum()

tensor(1924., dtype=torch.float64)

In [ ]:
!mkdir separed_timestamps/without_unknowns

In [ ]:
!mkdir separed_timestamps/without_unknowns/train
!mkdir separed_timestamps/without_unknowns/test

In [22]:
for i in range(0,35):
    torch.save(datas[i], 'separed_timestamps/without_unknowns/train/' + str(i + 1) + '.pt')
for i in range(35,49):
    torch.save(datas[i], 'separed_timestamps/without_unknowns/test/' + str(i + 1) + '.pt')